spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(RK860/2DxCSJiA6YCghFAc1dL3OMvLtO2GIE4izB9HtVz/AAMf32ZXV2qAaKYhKnUhuUrrcZHQmAYEE3/kgZPghfnOimfYafi/Yu3SRL82ENZweZX9WHSg==)
    username: ENC(pceESDIFw0AAXCB74qdBPg==)
    password: ENC(9NZFuDY0JD1m2HTDNjEi1Q==)
